# ==============================================================================
#  用於「預測階段」的最終設定檔
# ==============================================================================
#
# 說明：
# 這個版本只保留了構建模型架構所必需的參數。
# 所有與訓練過程相關的參數（如 optimizer, dataloader, k-fold 等）都已被移除，
# 因為 predict.py 在預測時並不需要它們。
#
# ==============================================================================

# --- 模型相關設定 (必須與訓練時完全一致) ---
model:
  # 預訓練的 ESM-2 模型
  esm_model_name: "facebook/esm2_t6_8M_UR50D"
  # esm_model_name 對應的嵌入維度
  esm_embedding_dim: 320 
  # 序列處理的最大長度
  max_len: 2048
  
  # 下游 Transformer 模型的參數
  d_model: 64        # 模型內部的工作維度
  n_head: 4          # 注意力頭的數量
  n_layer: 3         # Transformer 層數
  o_dim: 2           # 最終輸出維度